# pvc-uploader.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-uploader
  namespace: ${NAMESPACE} 
spec:
  containers:
    - name: uploader
      image: ubuntu:22.04
      command: ["/bin/bash"]
      args: ["-c", "sleep infinity"]
      volumeMounts:
        - mountPath: /workspace
          name: workspace
      stdin: true
      tty: true
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: nextflow-pvc
  restartPolicy: Never

